Feature/store summary#11
Couch-Coders/12th-Fun-Pyeon-log-be pull request #18
Opened 2022-11-30 12:27 UTC by DoKyeongOh

API 명세서에 작성된 섹션 중 Store에 해당하는 기능 구현했습니다. 

- StoreController, StoreService, StoreRepository, StoreDTO를 새로 만들었습니다.
- 특정 편의점에 대해 요약 정보를 넘겨줘야 하기 때문에 해당 편의점의 리뷰들을 List 형태로 받아와서 가공하도록 로직을 작성해봤습니다.
- 편의점 정보는 따로 DB에 저장하지 않기 때문에 Entity를 만들진 않았고, DTO를 만들고 리턴해서 Convertor에서 json으로 변환되도록 작성했습니다.

아래는 API 명세서 링크입니다.
https://www.notion.so/API-a947cc01e1e446649d8fc6e89b100108

2022-12-01 01:08 UTC, yourhrh reviewed
- StoreSummary 테이블을 따로 만들어 관리하는게 좋을 수 도 있겠네요

2022-12-01 01:08 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +            int sizeLimit = 3;
sizeLimit는 keyword sizeLimit일까요? sizeLimit의 경우 백엔드 단보다 클라이언트 단에서 받아서 처리하는게 좋습니다. 클라이언트 화면 크기에 따라 바뀔 수 있을것 같네요 
이름도 sizeLimit라고 하면 store의 limit같으니 keywordSizeLimit로 변경해주시는게 좋아보입니다.

2022-12-01 01:08 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +            storeDTO.setKeywordList(storeDTO.getKeywordList().subList(0,keywordCount));
해당 로직은 Service의 책임보다는 응답에 대한 storeDTO의 책임 같습니다.
keyword를 필터링 하는 로직은 storeDTO에 있는게 좋아보이네요

2022-12-01 01:08 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +            storeDTO.setKeywordList(storeDTO.getKeywordList().subList(0,keywordCount));
set함수를 override해서 사용해도 되고 의미가 있는 메서드를 만들어서 사용해도 됩니다. 너무 set에 의존할 필요는 없습니다.

2022-12-01 01:08 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +            StoreDTO storeDTO = getStoreSummary(storeId);
쿼리 횟수를 줄이기위해 한번에 가져와서 처리는 힘들까요?

2022-12-01 02:47 UTC, DoKyeongOh commented on src/main/java/com/example/demo/service/StoreService.java
> +            int sizeLimit = 3;
네 처음엔 정확한 이름을 명기하는게 좋지 않을까 했는데, 뭔가 코드가 옆줄로 길어지는 느낌이라 회피했었습니다.
명칭은 말씀하신대로 수정하겠습니다. 그리고 keywordSizeLimit도 querystring으로 받는 것도 프론트랑 이야기 해보겠습니다.

아니면 그냥 해당 keywordSizeLimit이라는 변수 자체를 없애고 리스트 전체를 넘겨줘서 프론트에서 알아서 사용하게 하는건 어떨까요?

2022-12-01 03:02 UTC, DoKyeongOh commented on src/main/java/com/example/demo/service/StoreService.java
> +            storeDTO.setKeywordList(storeDTO.getKeywordList().subList(0,keywordCount));
넵 위 코드는 편의점 하나의 요약 정보를 만든 뒤에 리스트를 자르는 부분인데, 이 부분을 storeDTO를 생성할때 생성자에서 자르도록 해보겠습니다.

2022-12-01 03:24 UTC, DoKyeongOh commented on src/main/java/com/example/demo/service/StoreService.java
> +            StoreDTO storeDTO = getStoreSummary(storeId);
확실히 편의점 갯수만큼 쿼리를 발생시켜야 하니까 성능상 좋지 않을 수도 있을 것 같습니다. 혹시 ReviewRepository에서 findByStoreIdIn() 메서드를 만들어보는건 어떨까요?

2022-12-01 05:01 UTC, yourhrh commented on src/main/java/com/example/demo/controller/StoreController.java
> +    public List<StoreDTO> storeSummaries(@RequestParam(value = "id", required = false) String[] storeIds){
@RequestParam(value="pageNo", required=false) String keywordSize
 요런식으로 받아서 처리하는게 좋아보입니다. 모바일 UI마다 키워드size가 다를 수 있습니다. 
 그런데 더보기 같은 기능을 넣으려면  그냥 다 보여주는 것도 괜찮습니다. (API 호출횟수 최소화)

2022-12-03 10:03 UTC, yourhrh requested changes

2022-12-03 10:03 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +        for (StoreSummary storeSummary : storeSummaries) {
꼭 DTO를 만들때 Builder 패턴을 쓸필요는 없습니다.
생성자에 storeSummary를 넣어주시는게 service 로직이 더 깔끔하고, 나중에 DTO 변경이 있을때도 활용하기 좋아보이네요

2022-12-03 10:03 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +    public List<String> getBestKeywordInReviewList(List<Review> reviewList) {
어디서 사용하는 메서드인가요?

2022-12-04 01:19 UTC, yourhrh requested changes

2022-12-04 01:19 UTC, yourhrh commented on src/test/java/com/example/demo/controller/StoreControllerTest.java
> +class StoreControllerTest {
@Transactional 을 붙여줘야지 테스트 후 DB가 롤백됩니다.

2022-12-04 01:19 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +        Optional<StoreSummary> optionalStoreSummary = storeSummaryRepository.findById(storeId);
optional의 orElseGet을 사용하면 4줄을 한줄로 바꿀 수 있습니다.

2022-12-04 01:19 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +        Optional<StoreSummary> optionalStoreSummary = storeSummaryRepository.findById(storeId);
https://mangkyu.tistory.com/70

2022-12-04 01:19 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +        StoreSummaryDTO storeSummaryDTO = StoreSummaryDTO.builder()
이것도 생성자로 하는 것으로 바꿔주세요

2022-12-04 13:50 UTC, yourhrh approved these changes

2022-12-04 13:50 UTC, merged