Feature/store summary#11
Couch-Coders/12th-Fun-Pyeon-log-be pull request #21
Opened 2022-12-12 05:29 UTC by DoKyeongOh

아래 내용에 대한 작업을 실시했습니다.

- StoreService.updateStoreSummary(storeId) : 편의점의 summary 정보를 업데이트하는 메소드
- StoreService.updateStoreKeywords(StoreSummary) : 편의점-키워드(StoreKeyword) 테이블에서 특정 편의점에 관련된 항목들을 업데이트하는 메소드
- StoreService.initKeywordContentMap(), getKeywordContent() : DB에 쿼리를 날리는 횟수를 줄이기 위해 만들었습니다.
- StoreService.keywordContentMap : DB에 쿼리를 날리는 횟수를 줄이기 위해 Map 형태의 필드로 만들었습니다.
- ReviewService.create/modify/delete Review() 메소드에 StoreService.updateStoreSummary() 추가했습니다.

일단 포스트맨으로 제가 생각했던 경우의 수대로 테스트해봤는데 이상은 없어보이는 상태입니다.

2022-12-12 06:59 UTC, yourhrh requested changes

2022-12-12 06:59 UTC, yourhrh commented on src/main/java/com/example/demo/service/ReviewService.java
> +        storeService.updateStoreSummary(storeId);
매번 전체를 읽어서 update 하면 너무 부하가 클것 같습니다. 차라리 ReviewService의 메서드에@Transactional 을 걸어 안전하게 하고 Review내용을 Summary 데이터에 추가하는건 어떨까요? 로직상 문제가 있나요>

2022-12-12 06:59 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +        if (storeSummary == null)
빈 SummaryDTO를 생성해서 리턴해주는 것은 어떨까요? null로 리턴하면 나중에 사용시 예기치 않은 에러가 발생할 가능성이 있습니다.

2022-12-12 08:15 UTC, DoKyeongOh commented on src/main/java/com/example/demo/service/ReviewService.java
> +        storeService.updateStoreSummary(storeId);
혹시 대략적으로 아래 내용처럼 바꾸는건 어떤지에 대해 말씀하시는건가요?

예를 들어 리뷰를 생성하는 경우라고 했을 때 
1. StoreSummary 테이블의 값을 읽어옵니다.
2. 자동으로 StoreKeyword도 함께 조회가 됩니다.
3. 별점 평균 : 별점 평균 x 리뷰 갯수로 총 별점의 합을 구한 뒤에 추가된 리뷰의 별점을 추가하여 평균을 구합니다.
4. 리뷰 갯수 : JpaRepository의 countBy~()로 구합니다.
5. StoreKeyword : StoreKeywordRepository.findByStoreId()로 데이터를 가져오고 방금 등록한 리뷰의 키워드를 가져와서 +1 연산을 실시합니다.
6. 위 3가지 (리뷰 수, 별점 평균, 편의점키워드)를 StoreSummary에 저장한 후 save()합니다.

일단 이런식으로 ReviewService에 독자적인 메소드를 추가할 수도 있을 것 같긴합니다.
로직만 작성하다보니 간결하게 끝내고싶은 생각이 생겨서 현재처럼 작성하긴 했는데 대략적으로 말씀하시는 내용이 위 내용과 같다면 말씀해주시면 이대로 작업 진행하겠습니다!

2022-12-12 08:17 UTC, yourhrh commented on src/main/java/com/example/demo/service/ReviewService.java
> +        storeService.updateStoreSummary(storeId);
네네 맞습니다.

2022-12-12 14:58 UTC, yourhrh requested changes

2022-12-12 14:58 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +        StoreSummary updatedSummary = StoreSummary.builder()
update시에는 save 없이 entity 에서 수정만 해줘도 테이블이 수정됩니다.

2022-12-12 14:58 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +        Long reviewCount = reviewRepository.countByStoreId(storeId).get();
이 밑에 부분은 전부 Entity안에 메서드로 들어가도 될 것 같네요. 
Service에 너무 많은 로직이 있습니다. 해당 내용이 Summary만 변경하는 것이면 Summary안에 넣어주시는 것이 단일 책임 원칙에 더 부합합니다.

2022-12-12 14:58 UTC, yourhrh commented on src/main/java/com/example/demo/service/StoreService.java
> +        Long reviewCount = reviewRepository.countByStoreId(storeId).get();
나머지 메서드들도 Service에 있는 로직들 중 Summary에 옮겨야 하는 것들은 옮기는게 좋아보입니다. Service에 너무 많은 코드가 들어있는 것이 좋은 패턴은 아닙니다

2022-12-13 06:39 UTC, DoKyeongOh commented on src/main/java/com/example/demo/service/StoreService.java
> +        Long reviewCount = reviewRepository.countByStoreId(storeId).get();
넵 제가 생각하기에 StoreSummary의 기능으로 사용할 수 있는 것들은 전부 StoreService -> StoreSummary로 옮겨서 작성했습니다.
포스트맨으로 테스트했을때는 잘 되는것 같았습니다

2022-12-13 07:31 UTC, yourhrh approved these changes

2022-12-13 07:31 UTC, merged